- name: Install Node.js
  block:
    - name: Download NodeSource setup script
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: "755"

    - name: Run NodeSource setup script
      ansible.builtin.command:
        cmd: /tmp/nodesource_setup.sh
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js 20
      ansible.builtin.package:
        name: nodejs
        state: present

- name: Install Yarn
  community.general.npm:
    name: yarn
    global: true

- name: Install pnpm
  community.general.npm:
    name: pnpm
    version: "10.9.0"
    global: true

- name: Download otp-ui
  ansible.builtin.git:
    repo: https://github.com/FabmobQC/otp-ui.git
    dest: "{{ frontend_otp_ui_folder }}"
    version: "e5ac412f1eef57bfc35e98275cad2d6013d51322"
  notify:
    - Install otp-ui's dependencies
    - Compile otp-ui

- name: Download otp-react-redux
  ansible.builtin.git:
    repo: https://github.com/FabmobQC/otp-react-redux.git
    dest: "{{ frontend_otp_react_redux_folder }}"
    version: "c887fb4e25e26e6f5aa64a047f2050ff471c1050"
    force: true
  notify:
    - Install otp-react-redux's dependencies
    - Compile otp-react-redux

- name: Deploy otp-react-redux configuration
  ansible.builtin.template:
    src: "{{ frontend_config_template_path }}"
    dest: "{{ frontend_config_path }}"
    mode: "755"
  notify:
    - Compile otp-react-redux

- name: Setup nginx for frontend
  ansible.builtin.include_role:
    name: nginx
  vars:
    # role_dir would resolve to nginx directory
    nginx_conf_file: "{{ playbook_dir }}/roles/frontend/templates/nginx_conf.j2"
    nginx_domain_name: "{{ frontend_domain_name }}"
