- name: Install dependencies
  ansible.builtin.package:
    name:
      - nodejs
      - npm
    state: present

- name: Install Yarn
  community.general.npm:
    name: yarn
    global: true


- name: Download otp-ui
  ansible.builtin.git:
    repo: https://github.com/FabmobQC/otp-ui.git
    dest: "{{ frontend_otp_ui_folder }}"
    version: "edd17628fe45fead7aa6ffe3d7e82a74b8029504"
  notify:
    - Install otp-ui's dependencies
    - Compile otp-ui

- name: Download otp-react-redux
  ansible.builtin.git:
    repo: https://github.com/FabmobQC/otp-react-redux.git
    dest: "{{ frontend_otp_react_redux_folder }}"
    version: "4f0ef32c0e97db5ea83194dfa43109e5edef7e9a"
    force: true
  notify:
    - Install otp-react-redux's dependencies
    - Compile otp-react-redux

- name: Deploy otp-react-redux configuration
  ansible.builtin.template:
    src: "{{ frontend_config_template_path }}"
    dest: "{{ frontend_config_path }}"
    mode: "755"
  notify:
    - Compile otp-react-redux

- name: Setup nginx for frontend
  ansible.builtin.include_role:
    name: nginx
  vars:
    # role_dir would resolve to nginx directory
    nginx_conf_file: "{{ playbook_dir }}/roles/frontend/templates/nginx_conf.j2"
    nginx_domain_name: "{{ frontend_domain_name }}"
