planificateur:
  hosts:
    planificateur.dazadillon.io:
      certbot_email: "communications@fabmobqc.ca"
      otp_version: 2.6.0
      planificateur_folder: "/root/planificateur"
      opentripplanner_local_data_folder: "files/opentripplanner_data_general"
      opentripplanner_api_domain: "otp-api.dazadillon.io"
      opentripplanner_upstream_url: "http://localhost:8080"
      otp_proxy_upstream_url: "http://localhost:3000"
      frontend_config_template_path: "templates/otp-react-redux_config.yaml.j2"
