planificateur:
  hosts:
    planmob.fabmobqc.ca:
      certbot_email: "communications@fabmobqc.ca"
      otp_version: 2.6.0
      planificateur_folder: "/root/planificateur"
      opentripplanner_local_data_folder: "files/opentripplanner_data_planmob"
      opentripplanner_api_domain: "api-otp.planmob.fabmobqc.ca"
      opentripplanner_upstream_url: "http://localhost:8080"
      opentripplanner_display_administrative_regions: true
      opentripplanner_display_amenities: true
      otp_proxy_upstream_url: "http://localhost:3000"
      frontend_config_template_path: "templates/otp-react-redux_config.yaml.j2"
      agencies:
        - agencyId: TACAL
          name: TACAL,Transport adapté et collectif d'Antoine-Labelle - TACAL
        - agencyId: TACL
          name: Transport adapté et collectif des Laurentides - TACL
        - agencyId: Ville de Tremblant
          name: Ville de Tremblant
        - agencyId: TAC RN,
          name: Transport adapté et collectif MRC Rivière-du-Nord - TAC
        - agencyId: exo
          name: exo
        - agencyId: ARG
          name: MRC d'Argenteuil
        - agencyId: 1
          name: Transport des personnes MRC de Bécancour
        - agencyId: TCME
          name: Transport collectif de la MRC de L'Érable
        - agencyId: Municar
          name: Municar
        - agencyId: victo
          name: Ville de Victoriaville
        - agencyId: DMV
          name: Ville de Drummondville
        - agencyId: mobilibus
          name: Mobilibus - Transport collectif et adapté dans la MRC de Drummond
        - agencyId: Bili
          name: Bili - Transport en commun et adapté de la MRC Nicolet-Yamaska
        - agencyId: Ville de Rouyn-Noranda
          name: Ville de Rouyn-Noranda
        - agencyId: TACT
          name: Transport adapté et collectif du Témiscamingue - TACT
        - agencyId: VdO
          name: Taxibus Val-d'Or