planificateur:
  hosts:
    planificateur.fabmobqc.ca:
      certbot_email: "communications@fabmobqc.ca"
      otp_version: 2.9.0
      planificateur_folder: "/root/planificateur"
      opentripplanner_local_data_folder: "files/opentripplanner_data_quebec-city"
      opentripplanner_api_domain: "www.api-otp.fabmobqc.ca"
      opentripplanner_upstream_url: "http://localhost:8080"

      otp_proxy_upstream_url: "http://localhost:3000"
      frontend_config_template_path: "templates/otp-react-redux-configs/quebec-city.yaml.j2"
