- name: Install Node.js
  block:
    - name: Download NodeSource setup script
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: "755"

    - name: Run NodeSource setup script
      ansible.builtin.command:
        cmd: /tmp/nodesource_setup.sh
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js 20
      ansible.builtin.package:
        name: nodejs
        state: present

- name: Download otp-proxy
  ansible.builtin.git:
    repo: https://github.com/FabmobQC/planificateur-otp-proxy.git
    dest: "{{ otp_proxy_folder }}"
    version: "54f7d4437ce068b75d603a53cb77a35697d04bb0"
  notify:
    - Compile otp-proxy

- name: Create otp-proxy service
  ansible.builtin.template:
    src: "otp-proxy.service.j2"
    dest: "/etc/systemd/system/otp-proxy.service"
    mode: "400"
  notify:
    - Reload systemd
    - Restart otp-proxy

- name: Install otp-proxy's dependencies
  community.general.npm:
    path: "{{ otp_proxy_folder }}"

- name: Setup nginx
  ansible.builtin.include_role:
    name: nginx
  vars:
    # role_dir would resolve to nginx directory
    nginx_conf_file: "{{ playbook_dir }}/roles/otp_proxy/templates/nginx_conf.j2"
    nginx_domain_name: "{{ opentripplanner_api_domain }}"
