---
- name: Planificateur FabMob QC
  hosts: planificateur
  become: true
  remote_user: root
  tasks:
    - name: Create Planificateur folder
      ansible.builtin.file:
        path: "{{ planificateur_folder }}"
        state: directory
        mode: "400"

    - name: Setup OpenTripPlanner
      ansible.builtin.include_role:
        name: opentripplanner
