---
- name: Planificateur FabMob QC
  hosts: planificateur
  become: true
  remote_user: root
  gather_facts: false
  tasks:
    - name: Create Planificateur folder
      ansible.builtin.file:
        path: "{{ planificateur_folder }}"
        state: directory
        mode: "400"

    - name: Setup OpenTripPlanner
      ansible.builtin.include_role:
        name: opentripplanner

    - name: Setup proxy
      ansible.builtin.include_role:
        name: otp_proxy

    - name: Setup frontend
      ansible.builtin.include_role:
        name: frontend
      vars:
        frontend_domain_name: "{{ inventory_hostname }}"
