---
- name: Planificateur FabMob QC
  hosts: planificateur
  become: true
  remote_user: root
  tasks:
    - name: Create Planificateur folder
      ansible.builtin.file:
        path: "{{ planificateur_folder }}"
        state: directory
        mode: "400"

    - name: Setup nginx
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_domain_name: "{{ opentripplanner_api_domain }}"
        nginx_upstream_url: "http://localhost:8080"

    - name: Setup OpenTripPlanner
      ansible.builtin.include_role:
        name: opentripplanner
